# Generated by Django 4.0.5 on 2022-06-22 10:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_location_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timing_type",
            field=models.CharField(
                choices=[("Single", "Single"), ("Recurring", "Recurring")],
                default="Single",
                max_length=100,
                verbose_name="timing_type",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tags can only contain letters, numbers and underscores",
                        regex="^[A-Za-z0-9_]+$",
                    )
                ],
                verbose_name="tag",
            ),
        ),
    ]
