# Generated by Django 4.0.5 on 2022-06-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
    ]
