# Generated by Django 4.0.5 on 2022-06-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_tag_remove_etype_event_remove_location_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="summary",
            field=models.CharField(max_length=150, verbose_name="summary"),
        ),
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="url"
            ),
        ),
    ]
