# Generated by Django 4.0.5 on 2022-07-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_remove_attendee_user_register_event_once_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="name"
            ),
        ),
    ]
