# Generated by Django 4.0.5 on 2022-07-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_attendee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_orders', to='events.attendee'),
        ),
    ]
