# Generated by Django 4.0.5 on 2022-07-26 22:19

import apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
