# Generated by Django 4.1 on 2022-08-18 05:15

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='GB', max_length=2, null=True, verbose_name='country'),
        ),
    ]
